insert


"R7" isa inference-rule,
lhs {match $x isa person;
$t isa tag;{$t has name 'Ludwig_van_Beethoven'} or {$t has name 'Johann_Sebastian_Bach'} or {$t has name 'Wolfgang_Amadeus_Mozart'};
($x, $t) isa tagging;
$y isa product, has name 'Chopin - Nocturnes';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R5" isa inference-rule,
lhs {match $x isa person;
$t isa tag;{$t has name 'Ozzy_Osbourne'} or {$t has name 'Rising_Force'};
($x, $t) isa tagging;
$y isa product;
{$y has name 'Ozzy Osbourne - Blizzard of Oz'} or {$y has name 'Fender Stratocaster'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

