insert

# motorbike
$motorbike isa category, id "motorbike", has name "motorbike";
$ducatti isa product, id "Ducatti-1299", has name "Ducatti 1299", has min-age 18, has gender "male";
(typed-product $ducatti, product-type $motorbike) isa typing;
(product-made $ducatti, product-origin country-81) isa made-in;

# music
$cd isa category, id "cd", has name "cd";
$theWall isa product, id "the-wall", has name "Pink Floyd - The Wall";
(typed-product $theWall,product-type $cd) isa typing;
$blizzard isa product, id "blizzard-of-ozz", has name "Ozzy Osbourne - Blizzard of Oz";
(typed-product $blizzard, product-type $cd) isa typing;
$nocturnes isa product, id "nocturnes", has name "Chopin - Nocturnes";
(typed-product $nocturnes, product-type $cd) isa typing;

# movie
$movie isa category, id "movie", has name "movie";
$goodBadUgly isa product, id "The-good-the-bad-the-ugly", has name "The Good, the Bad and the Ugly";
(typed-product $goodBadUgly, product-type $movie) isa typing;
$godfather isa product, id "Godfather", has name "Godfather";
(typed-product $godfather, product-type $movie) isa typing;
$dumb isa product, id "Dumb-and-dumber", has name "Dumb and dumber";
(typed-product $dumb, product-type $movie) isa typing;

# book
$book isa category, id "book", has name "book";
$dorianGray isa product, id "dorian-gray", has name "The Picture of Dorian Gray";
(typed-product $dorianGray, product-type $book) isa typing;
$colourOfMagic isa product, id "colour-of-magic", has name "The Colour of Magic";
(typed-product $colourOfMagic, product-type $book) isa typing;
$warOfWorlds isa product, id "war-of-the-worlds", has name "The War of the Worlds";
(typed-product $warOfWorlds, product-type $book) isa typing;
$crime isa product, id "crime-and-punishment", has name "Crime and Punishment";
(typed-product $crime, product-type $book) isa typing;
$farm isa product, id "animal-farm", has name "Animal Farm";
(typed-product $farm, product-type $book) isa typing;
$alice isa product, id "adventures-in-wonderland", has name "Alice's Adventures in Wonderland";
(typed-product $alice, product-type $book) isa typing;
$orientExpress isa product, id "orient-express", has name "Murder on the Orient Express";
(typed-product $orientExpress, product-type $book) isa typing;
$fairy isa product, id "fairy-tales", has name "Fairy Tales";
(typed-product $fairy, product-type $book) isa typing;
$jeeves isa product, id "my-man-jeeves", has name "My Man Jeeves";
(typed-product $jeeves, product-type $book) isa typing;
$rings isa product, id "lord-of-the-rings", has name "The Lord of the Rings";
(typed-product $rings, product-type $book) isa typing;
$harry isa product, id "harry-potter", has name "Harry Potter";
(typed-product $harry, product-type $book) isa typing;
$sherlock isa product, id "sherlock-holmes", has name "Stories of Sherlock Holmes";
(typed-product $sherlock, product-type $book) isa typing;
$forWhom isa product, id "for-whom-the-bell-tolls", has name "For Whom the Bell Tolls";
(typed-product $forWhom, product-type $book) isa typing;
$miceAndMen isa product, id "of-mice-and-men", has name "Of Mice and Men";
(typed-product $miceAndMen, product-type $book) isa typing;
$trial isa product, id "trial", has name "The Trial";
(typed-product $trial, product-type $book) isa typing;
$faust isa product, id "faust", has name "Faust";
(typed-product $faust, product-type $book) isa typing;


# paintings
$painting isa category, id "painting", has name "painting";
$lesElephants isa product, id "les-elephants", has name "Salvador Dali - Les Elephants";
(typed-product $lesElephants, product-type $painting) isa typing;
$waterLillies isa product, id "water-lillies", has name "Claude Monet - The Water Lillies";
(typed-product $waterLillies, product-type $painting) isa typing;
$nightWatch isa product, id "night-watch", has name "Rembrandt - The Night Watch";
(typed-product $nightWatch, product-type $painting) isa typing;
$monaLisa isa product, id "mona-lisa", has name "Leonardo da Vinci - Mona Lisa";
(typed-product $monaLisa, product-type $painting) isa typing;
$raphael isa product, id "madonna-of-the-pinks", has name "Raphael - The Madonna of the Pinks";
(typed-product $raphael, product-type $painting) isa typing;
$bacchus isa product, id "bacchus-and-ariadne", has name "Titian - Bacchus and Ariadne";
(typed-product $bacchus, product-type $painting) isa typing;
$sunflowers isa product, id "sunflowers", has name "Vincent van Gogh - Sunflowers";
(typed-product $sunflowers, product-type $painting) isa typing;
$universe isa product, id "controller-of-the-universe", has name "Diego Rivera - Controller of the Universe";
(typed-product $universe, product-type $painting) isa typing;
$grayTree isa product, id "gray-tree", has name "Piet Mondrian - Gray Tree";
(typed-product $grayTree, product-type $painting) isa typing;
$lastJudgement isa product, id "last-judgement", has name "Michelangelo - The Last Judgement";
(typed-product $lastJudgement, product-type $painting) isa typing;

# instrument
$guitar isa category, id "guitar", has name "guitar";
$stratocaster isa product, id "stratocaster", has name "Fender Stratocaster";
(typed-product $stratocaster, product-type $guitar) isa typing;

# bands
"category-61" isa category, id "category-61", has name "Band";
"category-115" isa category, id "category-115", has name "MusicalArtist";

$beatles isa tag, id "beatles", has name "The Beatles";
(grouped-tag $beatles,tag-group category-61) isa grouping;
$pinkFloyd isa tag, id "pink-floyd", has name "Pink Floyd";
(grouped-tag $pinkFloyd,tag-group category-61) isa grouping;
$rollingStones isa tag, id "rolling-stones", has name "Rolling Stones";
(grouped-tag $rollingStones,tag-group category-61) isa grouping;
$cream isa tag, id "cream", has name "Cream";
(grouped-tag $cream,tag-group category-61) isa grouping;
$yardbirds isa tag, id "yardbirds", has name "The Yardbirds";
(grouped-tag $yardbirds,tag-group category-61) isa grouping;
$simonAndGarfunkel isa tag, id "simon-and-garfunkel", has name "Simon and Garfunkel";
(grouped-tag $simonAndGarfunkel,tag-group category-61) isa grouping;
$blackSabbath isa tag, id "black-sabbath", has name "Black Sabbath";
(grouped-tag $blackSabbath,tag-group category-61) isa grouping;
$wailers isa tag, id "bob-marley-and-the-wailers", has name "Bob Marley and the Wailers";
(grouped-tag $wailers,tag-group category-61) isa grouping;

$buckethead isa tag, id "buckethead", has name "Buckethead";
(grouped-tag $buckethead,tag-group category-61) isa grouping;

$primus isa tag, id "primus", has name "Primus";
(grouped-tag $primus, tag-group category-61) isa grouping;

$linkinPark isa tag, id "linkin-park", has name "Linkin Park";
(grouped-tag $linkinPark, tag-group category-61) isa grouping;

$limpBizkit isa tag, id "limp-bizkit", has name "Limp Bizkit";
(grouped-tag $limpBizkit, tag-group category-61) isa grouping;

$jimiHendrix isa tag, id "jimi-hendrix", has name "Jimi Hendrix";
(grouped-tag $jimiHendrix, tag-group category-115) isa grouping;

$slash isa tag, id "slash", has name "Slash";
(grouped-tag $slash, tag-group category-115) isa grouping;

$yngwie isa tag, id "yngwie-malmsteen", has name "Yngwie Malmsteen";
(grouped-tag $yngwie, tag-group category-115) isa grouping;

$steveVai isa tag, id "steve-vai", has name "Steve Vai";
(grouped-tag $steveVai, tag-group category-115) isa grouping;

$cacophony isa tag, id "cacophony", has name "Cacophony";
(grouped-tag $cacophony, tag-group category-61) isa grouping;

$vanHalen isa tag, id "van-halen", has name "van Halen";
(grouped-tag $vanHalen, tag-group category-61) isa grouping;

$metallica isa tag, id "metallica", has name "Metallica";
(grouped-tag $metallica, tag-group category-61) isa grouping;

$megadeth isa tag, id "megadeth", has name "Megadeth";
(grouped-tag $megadeth, tag-group category-61) isa grouping;

$slayer isa tag, id "slayer", has name "Slayer";
(grouped-tag $slayer, tag-group category-61) isa grouping;

$pantera isa tag, id "pantera", has name "Pantera";
(grouped-tag $pantera, tag-group category-61) isa grouping;

$superjoint isa tag, id "superjoint", has name "Superjoint Ritual";
(grouped-tag $superjoint, tag-group category-61) isa grouping;

$ironMaiden isa tag, id "iron-maiden", has name "Iron Maiden";
(grouped-tag $ironMaiden, tag-group category-61) isa grouping;

$judasPriest isa tag, id "judasPriest", has name "Judas Priest";
(grouped-tag $judasPriest, tag-group category-61) isa grouping;

$thinLizzy isa tag, id "thin-lizzy", has name "Thin Lizzy";
(grouped-tag $thinLizzy, tag-group category-61) isa grouping;

$ledZeppelin isa tag, id "led-zeppelin", has name "Led Zeppelin";
(grouped-tag $ledZeppelin, tag-group category-61) isa grouping;

$deepPurple isa tag, id "deep-purple", has name "Deep Purple";
(grouped-tag $deepPurple, tag-group category-61) isa grouping;

$queen isa tag, id "queen", has name "Queen";
(grouped-tag $queen, tag-group category-61) isa grouping;

tag plays-role recommended-product;

