insert

#transitivity of resides & sublocate
"R1" isa inference-rule,
lhs {match (located-subject $x, subject-location $y) isa resides;
(member-location $y, container-location $z) isa sublocate;
select $x, $z},
rhs {match (located-subject $x, subject-location $z) isa resides};
#introduces ambiguity in rule ->rhs {match ($x, $z) isa resides};

# transitivity of sublocate
"R2" isa inference-rule,
lhs {match
(member-location $x, container-location $y) isa sublocate;
(member-location $y, container-location $z) isa sublocate;
select $x, $z},
rhs {match (member-location $x, container-location $z) isa sublocate};

"R3" isa inference-rule,
lhs {match ($x, $y) isa moderates},
rhs {match ($x, $y) isa membership};

"R4" isa inference-rule,
lhs {match $x isa person;
$t1 isa tag;$t1 id 'Ennio Morricone';
$t2 isa tag;$t2 id 'John Wayne';
($x, $t1) isa tagging;
($x, $t2) isa tagging;
$y isa product;
$y has name 'The Good, the Bad and the Ugly';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R5" isa inference-rule,
lhs {match $x isa person;
$t isa tag;{$t has name 'Ozzy_Osbourne'} or {$t has name 'Rising_Force'};
($x, $t) isa tagging;
$y isa product;
{$y has name 'Ozzy Osbourne - Blizzard of Oz'} or {$y has name 'Fender Stratocaster'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R6" isa inference-rule,
lhs {match $x isa person;
$x has gender 'male';$x has age >=18;
$y isa product;$y has min-age >=18;
$z isa country;$z has name 'Italy';
($y, $z) isa made-in;
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R7" isa inference-rule,
lhs {match $x isa person;
$t isa tag;{$t has name 'Ludwig_van_Beethoven'} or {$t has name 'Johann_Sebastian_Bach'} or {$t has name 'Wolfgang_Amadeus_Mozart'};
($x, $t) isa tagging;
$y isa product, has name 'Chopin - Nocturnes';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R8" isa inference-rule,
lhs {match $x isa person;
$t isa tag;$t has name 'Roger_Waters';
($x, $t) isa tagging;
$y isa product, has name 'Pink Floyd - The Wall';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

###########################################
##################Writer->Book######################
#############################################

#"R9" isa inference-rule,
#lhs {select $x, $y where
#$x isa person;$t isa tag;
#($x, $t) isa tagging;
#$tt isa category;$tt has name 'Writer';
#($t, $tt) isa grouping;
#$y isa product;
#$yt isa category;$yt has name 'book';
#($y, $yt) isa typing},
#rhs {select $x, $y where
#($x, $y) isa recommendation};

"R10" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'H._G._Wells';
($x, $t) isa tagging;
$y isa product, has name 'The War of the Worlds';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R11" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Fyodor_Dostoyevsky';
($x, $t) isa tagging;
$y isa product, has name 'Crime and Punishment';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R12" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'George_Orwell';
($x, $t) isa tagging;
$y isa product, has name 'Animal Farm';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R13" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Lewis_Carroll';
($x, $t) isa tagging;
$y isa product, has name 'Alice\'s Adventures in Wonderland';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R14" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Agatha_Christie';
($x, $t) isa tagging;
$y isa product, has name 'Murder on the Orient Express';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R15" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Hans_Christian_Andersen';
($x, $t) isa tagging;
$y isa product, has name 'Fairy Tales';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R16" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Terry_Pratchett';
($x, $t) isa tagging;
$y isa product, has name 'The Colour of Magic';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R17" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'P._G._Wodehouse';
($x, $t) isa tagging;
$y isa product, has name 'My Man Jeeves';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R18" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Oscar_Wilde';
($x, $t) isa tagging;
$y isa product, has name 'The Picture of Dorian Gray';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R19" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'J._R._R._Tolkien';
($x, $t) isa tagging;
$y isa product, has name 'The Lord of the Rings';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R20" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'J._K._Rowling';
($x, $t) isa tagging;
$y isa product, has name 'Harry Potter';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R21" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Arthur_Conan_Doyle';
($x, $t) isa tagging;
$y isa product, has name 'Stories of Sherlock Holmes';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R22" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Ernest_Hemingway';
($x, $t) isa tagging;
$y isa product, has name 'For Whom the Bell Tolls';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R23" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'John_Steinbeck';
($x, $t) isa tagging;
$y isa product, has name 'Of Mice and Men';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R24" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Franz_Kafka';
($x, $t) isa tagging;
$y isa product, has name 'Stories of The Trial';
select $x, $y },
rhs {match ($x, $y) isa recommendation};

"R25" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Johann_Wolfgang_von_Goethe';
($x, $t) isa tagging;
$y isa product, has name 'Faust';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

############################################
##############MusicalArtist->Band############
#############################################

"R26" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Ozzy_Osbourne';
($x, $t) isa tagging;
$y isa tag, has name 'Black Sabbath',
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R27" isa inference-rule,
lhs {match $x isa person;
$t isa tag;{$t has name 'Paul_McCartney'} or {$t has name 'George_Harrison'};
($x, $t) isa tagging;
$y isa tag, has name 'The Beatles';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R28" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Roger_Waters';
($x, $t) isa tagging;
$y isa tag, has name 'Pink Floyd';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R29" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Keith_Richards';
($x, $t) isa tagging;
$y isa tag, has name 'Rolling Stones';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R30" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Paul_Simon';
($x, $t) isa tagging;
$y isa tag, has name 'Simon and Garfunkel';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R31" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Eric_Clapton';
($x, $t) isa tagging;
$y isa tag;
{$y has name 'Cream'} or {$y has name 'The Yardbirds'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R32" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Bob_Marley';
($x, $t) isa tagging;
$y isa tag, has name 'Bob Marley and the Wailers';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

############################################
##############Album->Band##################
#############################################

"R33" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Master_of_Puppets';
($x, $t) isa tagging;
$y isa tag;
{$y has name 'Megadeth'} or {$y has name 'Slayer'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R34" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Far_Beyond_Driven';
($x, $t) isa tagging;
$y isa tag;
{$y has name 'Pantera'} or {$y has name 'Superjoint Ritual'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R35" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Hybrid_Theory';
($x, $t) isa tagging;
$y isa tag;
{$y has name 'Linkin Park'} or {$y has name 'Limp Bizkit'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R36" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Powerslave';
($x, $t) isa tagging;
$y isa tag;
{$y has name 'Iron Maiden'} or {$y has name 'Judas Priest'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R37" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Enter_the_Chicken';
($x, $t) isa tagging;
$y isa tag;
{$y has name 'Buckethead'} or {$y has name 'Primus'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R38" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Rising_Force';
($x, $t) isa tagging;
$y isa tag;
{$y has name 'Yngwie Malmsteen'} or {$y has name 'Steve Vai'} or {$y has name 'Cacophony'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R39" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Led_Zeppelin_IV';
($x, $t) isa tagging;
$y isa tag;
{$y has name 'Led Zeppelin'} or {$y has name 'Deep Purple'};
select $x, $y},
rhs {match ($x, $y) isa recommendation};

############################################
##############Song/Single->Band##################
#############################################

"R40" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'All_Along_the_Watchtower';
($x, $t) isa tagging;
$y isa tag, has name 'Jimi Hendrix';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R41" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'These_Are_the_Days_of_Our_Lives';
($x, $t) isa tagging;
$y isa tag, has name 'Queen';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R42" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Come_Together';
($x, $t) isa tagging;
$y isa tag, has name 'The Beatles';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R43" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Smoke_on_the_Water';
($x, $t) isa tagging;
$y isa tag, has name 'Deep Purple';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R44" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Immigrant_Song';
($x, $t) isa tagging;
$y isa tag, has name 'Led Zeppelin';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

######################################################
##################Artist->Painting####################
#######################################################

"R45" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Claude_Monet';
($x, $t) isa tagging;
$y isa product, has name 'Claude Monet - The Water Lillies';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R46" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Rembrandt';
($x, $t) isa tagging;
$y isa product, has name 'Rembrandt - The Night Watch';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R47" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Leonardo_da_Vinci';
($x, $t) isa tagging;
$y isa product, has name 'Leonardo da Vinci - Mona Lisa';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R48" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Raphael';
($x, $t) isa tagging;
$y isa product, has name 'Raphael - The Madonna of the Pinks';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R49" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Titian';
($x, $t) isa tagging;
$y isa product, has name 'Titian - Bacchus and Ariadne';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R50" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Vincent_van_Gogh';
($x, $t) isa tagging;
$y isa product, has name 'Vincent van Gogh - Sunflowers';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R51" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Diego_Rivera';
($x, $t) isa tagging;
$y isa product, has name 'Diego Rivera - Controller of the Universe';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R52" isa inference-rule,
lhs {match $x isa person;
$t isa tag, has name 'Piet_Mondrian';
($x, $t) isa tagging;
$y isa product, has name 'Piet Mondrian - Gray Tree';
select $x, $y},
rhs {match ($x, $y) isa recommendation};

"R53" isa inference-rule,
lhs {match $x isa person;$t isa tag, has name 'Michelangelo';
($x, $t) isa tagging;
$y isa product, has name 'Michelangelo - The Last Judgement';
select $x, $y},
rhs {match ($x, $y) isa recommendation};
