insert

"University of Cambridge" isa university;
"Mindmaps" isa company;
"Cambridge" isa city;
"London" isa city;
"UK" isa country;
"country-81" isa country, has name "Italy";
"Europe" isa continent;
"Alice" isa person;
"Bob" isa person;
"Bob" has age 21, has name "Bob", has gender "male";
"Charlie" isa person, has name "Charlie";
"Denis" isa person, has name "Denis";
"Frank" isa person, has name "Frank";
"Gary" isa person, has name "Gary";
"Karl Fischer" isa person, has name "Karl Fischer";
"forum1" isa forum;

(located-subject 'University of Cambridge', subject-location Cambridge) isa resides;
(located-subject 'Mindmaps', subject-location London) isa resides;
(member-location Cambridge, container-location UK) isa sublocate;
(member-location London, container-location UK) isa sublocate;
(member-location UK, container-location Europe) isa sublocate;
(moderator Bob, moderated forum1) isa moderates;

"Ennio Morricone" isa tag, has name "Ennio_Morricone";
"John Wayne" isa tag, has name "John_Wayne";
"Ozzy Osbourne" isa tag, has name "Ozzy_Osbourne";
"Rising Force" isa tag, has name "Rising_Force";
"Terry Pratchett" isa tag, has name "Terry_Pratchett";
"H. G. Wells" isa tag, has name "H._G._Wells";
"Oscar Wilde" isa tag, has name "Oscar_Wilde";
"Johann Wolfgang von Goethe" isa tag, has name "Johann_Wolfgang_von_Goethe";
"Writer" isa category;
(grouped-tag 'Terry Pratchett', tag-group Writer) isa grouping;
(grouped-tag 'H. G. Wells', tag-group Writer) isa grouping;
(grouped-tag 'Johann Wolfgang von Goethe', tag-group Writer) isa grouping;

"Johann_Sebastian_Bach" isa tag, has name "Johann_Sebastian_Bach";
"Ludwig_van_Beethoven" isa tag, has name "Ludwig_van_Beethoven";
"Wolfgang_Amadeus_Mozart" isa tag, has name "Wolfgang_Amadeus_Mozart";

"Roger_Waters" isa tag, has name "Roger_Waters";

(tagged-subject Alice, subject-tag 'H. G. Wells') isa tagging;
(tagged-subject Bob, subject-tag 'Ennio Morricone') isa tagging;
(tagged-subject Bob, subject-tag 'John Wayne') isa tagging;
(tagged-subject Denis, subject-tag 'Terry Pratchett') isa tagging;
(tagged-subject Denis, subject-tag 'Oscar Wilde') isa tagging;
(tagged-subject Frank, subject-tag 'Ludwig_van_Beethoven') isa tagging;

(tagged-subject Charlie, subject-tag 'Ozzy Osbourne') isa tagging;
(tagged-subject Charlie, subject-tag 'Rising Force') isa tagging;
(tagged-subject Gary, subject-tag 'Roger_Waters') isa tagging;

(tagged-subject 'Karl Fischer', subject-tag 'Ludwig_van_Beethoven') isa tagging;
(tagged-subject 'Karl Fischer', subject-tag 'Wolfgang_Amadeus_Mozart') isa tagging;
(tagged-subject 'Karl Fischer', subject-tag 'Johann Wolfgang von Goethe') isa tagging;