insert

#recommend Cabernet Sauvignion
"Alice" isa person;
Alice has preferred-context "aperitif";
Alice has preferred-sparklingness "non-sparkling";
Alice has preferred-body "full";
Alice has preferred-colour "red";

#recommend White Champagne
"Bob" isa person;
Bob has preferred-context "aperitif";
Bob has preferred-sparklingness "sparkling";
Bob has preferred-body "full";
Bob has preferred-colour "white";

#recommend Pinot Grigio
"Charlie" isa person;
Charlie has preferred-context "entree";
Charlie has preferred-entree "white meat";
Charlie has preferred-colour "rose";

#recommend Busuioaca Romaneasca
"Denis" isa person;
Denis has preferred-context "entree";
Denis has preferred-entree "steak";
Denis has preferred-colour "rose";

#recommend Tamaioasa Romaneasca
"Eva" isa person;
Eva has preferred-context "aperitif";
Eva has preferred-body "full";
Eva has preferred-sparklingness "non-sparkling";
Eva has preferred-colour "white";

#recommend Riojo Blanco
"Frank" isa person;
Frank has preferred-context "entree";
Frank has preferred-entree "barbecue";
Frank has preferred-body "full";
Frank has preferred-sparklingness "non-sparkling";
Frank has preferred-colour "white";

#wines
"White Champagne" isa wine;
"Cabernet Sauvignion" isa wine;
"Tamaioasa Romaneasca" isa wine;
"Busuioaca Romaneasca" isa wine;
"Pinot Noir" isa wine;
"Muscat Sec" isa wine;
"Pinot Grigio Rose" isa wine;
"Corbieres 2003" isa wine;
"Chateau Agnel 2000" isa wine;
"Rosso di Sicilia 2004" isa wine;
"Riojo Blanco CVNE 2003" isa wine;
"Tamaioasa Regala" isa wine;
"Riojo Tempranillo" isa wine;
"Chianti" isa wine;
"White Riesling" isa wine;
"Burgundy" isa wine;
"Chardonnay" isa wine;
"Bordeaux Blanc" isa wine;
"Feteasca Regala" isa wine;
"Feteasca Roz" isa wine;
"Feteasca Neagra" isa wine;
"Sauvignion Blanc" isa wine;
